### ISSUE TITLE
doing stuff to get used to the languages

### ISSUE THREAD

**Issue by Reaster0** [Reaster0/ft_transcendence#1]
personnaly i tested nestjs for a couple of days and clearly this need some experimentations to get used to
for the moment the best project/tuto i've followed is this one : https://wanago.io/2020/05/11/nestjs-api-controllers-routing-module/

**Comment by LesChats** [comment]
I tested nestJs 2 days, I get the basic understanding ( still I should have do more ) of the beast. Ready to go :O !

**Comment by Ala-Na** [comment]
I think we're all good with this issue =)
