### ISSUE TITLE
Vue warning for vuetify elements

### ISSUE THREAD

**Issue by Ala-Na** [Reaster0/ft_transcendence#102]
On chat page, warning as displayed inside console :
`[Vue warn]: Failed to resolve component: v-subheader`

This warning pops up for v-subheader, v-list-item-group, v-list-item-content, v-tabs-slider and v-tabs-item which are all vuetify elements. I tried to fix this, but solutions I found on the mighty internet were mostly JS compatible and not TS, or were not working.

It's only warnings and elements are correctly displayed, so I guess we can ignore them. But I still do my duty to report =)

**Comment by LesChats** [comment]
Nadège rules !
