### ISSUE TITLE
User setting edit

### ISSUE THREAD

**Issue by LesChats** [Reaster0/ft_transcendence#108]
the editing of users setting is broken....

when changing nickname where sending bad request at each new character entry.
that eventually lead the all page to brake (here the avatar as suddenly disappear)

<img width="1271" alt="Screen Shot 2022-06-22 at 1 51 29 PM" src="https://user-images.githubusercontent.com/51509223/175023025-4f820449-8203-4ba6-b234-8aae4c59556b.png">

**Comment by Ala-Na** [comment]
I think it's "normal" for the avatar to disappear. You can see the giant cloud icon as a button "upload your avatar". If you return to main account page, the new avatar selected should appears. But yeah, the bad request stuff is more worrying, as it pops each time we go to the user page.

**Comment by Reaster0** [comment]
yeah the avatar dosen't disappear i don't show it at all, and i don't send bed request i just send a request to change the nickname each time the user change the nickname, it would be the same thing if i put a button "send new username" if the backend send no as a response (400) it's just a reponse from the backend when the nickname is invalid, if you want you can change the code sended when there is an invalid nickname and it would not show as red but it's not an issue really
(and yes i send it once at the start of the page i can't really change it but it's not a problem)

**Comment by LesChats** [comment]
I thing were not suppose to get red error message popping up at any time of the process.
Still the page is doing weird stuff will Im adding characters to the field.
(first append when you add 5 character the page "format" change.

The logic of sending a backend + dataBase request to update de name at each input seems doubtful...

thx for the explanation about the "bug" logic, sorry for my misinterpretation 😅

**Comment by Ala-Na** [comment]
Ah yeah, good idea ! Forgot to implement them after we decided of nickname actual implementation. Something other than alphanum should not work though typeorm would send an error according to entities set up, but previous check would be better.

**Comment by LesChats** [comment]
<img width="736" alt="Screen Shot 2022-06-22 at 7 26 55 PM" src="https://user-images.githubusercontent.com/51509223/175100133-3bb43245-a5a4-4b44-8c6a-b5b039c464fb.png">

**Comment by Ala-Na** [comment]
Well, I guess class-validator doesn't work as I hoped for entities

**Comment by LesChats** [comment]
im correcting everything. no more red light

**Comment by Reaster0** [comment]
so you've just send another code as response?

**Comment by LesChats** [comment]
no preventing to try update if the newNickname is not different from the old one.
everything is ok know <3
