### ISSUE TITLE
spectator mode

### ISSUE THREAD

**Issue by LesChats** [Reaster0/ft_transcendence#112]
<img width="711" alt="Screen Shot 2022-06-22 at 10 14 12 PM" src="https://user-images.githubusercontent.com/51509223/175127843-242215d6-979c-4c74-b373-15943f3f0a29.png">

**Comment by Ala-Na** [comment]
@Reaster0 is it fully working ? If so, please close this issue.

**Comment by Reaster0** [comment]
Yes the watching mode is working, i just need to implement a button in the friend list to see it and implement a little tweak to make it work from the friend list ;)

**Comment by Reaster0** [comment]
#126 improve the watchGame system to let us do that
