### ISSUE TITLE
Deployment solution

### ISSUE THREAD

**Issue by Reaster0** [Reaster0/ft_transcendence#12]
for the deployment we have i think two solutions, we can have a nginx docker that load balance the traffic between our / and /api route (frontend and backend respectively)
or using nest serve-static to directly serve the builded vue files (i kinda like this solution because that mean we need one less container)
this thread is good to make an idea of it
https://www.reddit.com/r/Nestjs_framework/comments/lxaztu/how_do_you_implement_your_frontend_build_deploy/

**Comment by LesChats** [comment]
still an issue ?

**Comment by Ala-Na** [comment]
Just as a reminder: `docker-compose up --build` is the command we should use to launch our app

**Comment by Reaster0** [comment]
ho wait no it's not an issue since aaaa an old commit lmao
