### ISSUE TITLE
Disable 2FA

### ISSUE THREAD

**Issue by Ala-Na** [Reaster0/ft_transcendence#120]
A system for disabling 2FA should be made, according to correction =/

**Comment by Ala-Na** [comment]
For now, there is only one function disable2FA inside user.service.ts but it's not called by the controller

**Comment by LesChats** [comment]
OK I can go on that tomorrow if it still a must do by then.

**Comment by Reaster0** [comment]
i can do it tomorrow on the front and @LesChats make a route for it :')

**Comment by LesChats** [comment]
added the route, didn't test it, tell me ;)
it's a patch route for trolling purpose ;) <3

<img width="709" alt="Screen Shot 2022-06-25 at 12 22 53 PM" src="https://user-images.githubusercontent.com/51509223/175769481-4909f218-1d9c-4cf2-902d-567439baf9d5.png">

**Comment by LesChats** [comment]
working

**Comment by Reaster0** [comment]
fixed in #127
