### ISSUE TITLE
Access watch game from chat

### ISSUE THREAD

**Issue by Ala-Na** [Reaster0/ft_transcendence#121]
According to correction, accessing a match of a player should be done from chat or friend interface.
I made the logic for it inside chat interface and started it on `TheGame.vue`.

@Reaster0, I put some `TODO` comments where the rest of the logic should be implemented. It may need some variables manipulations to have the correct display. Can you please continue it ?

**Comment by Reaster0** [comment]
No worries i'll do it tomorrow!

**Comment by Reaster0** [comment]
it's done (almost) in #126
