### ISSUE TITLE
No same option game found

### ISSUE THREAD

**Issue by LesChats** [Reaster0/ft_transcendence#128]
<img width="1417" alt="Screen Shot 2022-06-25 at 5 35 31 PM" src="https://user-images.githubusercontent.com/51509223/175780526-c9bae0ba-90ab-4f80-aec0-55a028d0c270.png">

**Comment by Reaster0** [comment]
? it dosen't work like that, each player put their parameters and then the game is playing with the average (i think or it's a 50/50 chance) of both parameters

**Comment by LesChats** [comment]
<img width="1410" alt="Screen Shot 2022-06-25 at 5 40 16 PM" src="https://user-images.githubusercontent.com/51509223/175780744-631e9bbc-0242-4b8d-9f78-eb6240fdb0a4.png">

**Comment by Reaster0** [comment]
you can test it by playing the game

**Comment by LesChats** [comment]
didn't test further this behavior... Yes I will

**Comment by LesChats** [comment]
look like it take the option of the first player searching for a game... we should test the behavior whit multiple players 😂

**Comment by Reaster0** [comment]
that's @Ala-Na that know how it work :')

**Comment by Ala-Na** [comment]
Normally it's a mean between the two players options. You can see more details about it inside equilibrateFeatures function
