### ISSUE TITLE
disconnect outside game

### ISSUE THREAD

**Issue by LesChats** [Reaster0/ft_transcendence#129]
<img width="658" alt="Screen Shot 2022-06-25 at 5 40 27 PM" src="https://user-images.githubusercontent.com/51509223/175780807-da4387a5-231c-43d8-b34f-fa0c5e1f037c.png">

just after matching, but before accepting the matching (no game launched) if one wannabe player quit the lobby the other player is forceful disconnect and redirect to home page.

**Comment by Reaster0** [comment]
that's also an expected behaviour don't worry that's because you should anyway refresh the page if the matched adversary quit

**Comment by LesChats** [comment]
ok you can close, just felt weird to get redirect to home before even agreed on the matching.
