### ISSUE TITLE
chat blink on new message

### ISSUE THREAD

**Issue by LesChats** [Reaster0/ft_transcendence#131]
This may be coming from the last Chat PR that enable ordering channel by update date.
but now the chat is blinking on each new message.... very disturbing.
Find solution or downgrade :(

**Comment by Ala-Na** [comment]
Yeah, things tend to blink once an element is modified as it's being remade. Idk how to fix this behaviour except rethinking the whole system. I'll try to find tomorrow if there's a way to soften this effect. It's ugly but not a bug.

**Comment by Ala-Na** [comment]
I found the problem ! It wasn't really a simple bleaking, it was a 'reset' of channel because of the call to initDisplayChannel, which is called by channelList message received from back. I found a solution, but I'll try to find something to avoid sending channelList each time a message is sent.

**Comment by LesChats** [comment]
me to... now im trying to resolve big conflict 😅
