### ISSUE TITLE
warning about jwt cookie "samesite"

### ISSUE THREAD

**Issue by Reaster0** [Reaster0/ft_transcendence#36]
when working on the emplementation of the 2fa system i come accross this warning, is this a problem?
<img width="1673" alt="Capture d’écran 2022-05-18 à 23 18 17" src="https://user-images.githubusercontent.com/73885131/169157593-a14e2f3b-112e-4d81-be3d-91aa473898a0.png">

**Comment by LesChats** [comment]
ok thx. I corrected it, it will be part of the incoming update
