### ISSUE TITLE
work on the websocket communications

### ISSUE THREAD

**Issue by Reaster0** [Reaster0/ft_transcendence#49]

**Comment by Ala-Na** [comment]
Working on it for game part but it may take a few days to construct something clean enough to be used by frontend.

**Comment by Ala-Na** [comment]
Btw, don't think we can set up swagger documentation for WebSocketGateway =( Will try to make a resume of it with PR.

**Comment by LesChats** [comment]
Same I’m completely into the all basic structure and database stuff. Plus I’m moving today and tomorrow maybe Monday a bit. But then I will be at school maybe every day as know i will be Ethan neighbour 😈

just saying don’t expect anything concrete before Wednesday on chat part. But surely I’ll deliver something solide by the end of next week.

**Comment by Ala-Na** [comment]
Think we're good for basics
