### ISSUE TITLE
issue with the /user/settings route

### ISSUE THREAD

**Issue by Reaster0** [Reaster0/ft_transcendence#51]
when i make a request to the route using patch and with a correct json body, i get the answer 200 and there's still no modification in the db, did i make a mistake or the route is not ready yet?
<img width="528" alt="Capture d’écran 2022-05-23 à 12 06 35" src="https://user-images.githubusercontent.com/73885131/169796607-143426c7-dfff-409b-8bf4-1d4abf68bc4d.png">

**Comment by LesChats** [comment]
The route was setup by myself. The logic is pretty straightforward so the error is unlikely coming from that. But still I’m quite a newborn regarding database handler and I may have misused the repository.save() methode. Nadège will need to take a look on that matter

**Comment by Ala-Na** [comment]
Not sure where the problem comes from, as I can't really test it in real conditions with cookies from back only.  I modified a little the function called inside the route, tell me if it's sufficient.

**Comment by Ala-Na** [comment]
Seems to be working now, please merge corresponding PR
