### ISSUE TITLE
Redirect user to TwoFAPage when TwoFA is enabled

### ISSUE THREAD

**Issue by Ala-Na** [Reaster0/ft_transcendence#85]
After an user enabled 2FA : When user click on "login" and after he completed 42 auth, user is redirected to home page. User have to click a second time on "login" and then put the 2FA code before being considered as login.
A possible improvement would be to redirect user to the page asking for 2FA code right after 42 auth, if possible ?

**Comment by Reaster0** [comment]
wait? that's really weird because it don't work like that for me, are you sure that on your side the login callback is /login and not only / ?

**Comment by Ala-Na** [comment]
In the .env file ? If so, maybe it'll better to write it without calling process.env value as it can be modified ?

**Comment by Reaster0** [comment]
yeah i think we where using this solution because we've changed the route often at the start, you can try to hardcode it if it not lock the usage of localhost haha

**Comment by Ala-Na** [comment]
Seems like we can't do a simple ('http://:port/login') like for front =/ Too bad, we have to keep it inside .env for now
