### ISSUE TITLE
Others users infos

### ISSUE THREAD

**Issue by Ala-Na** [Reaster0/ft_transcendence#87]
An user should be able to access other users informations and stats, according to subject

**Comment by Ala-Na** [comment]
List of potentials helpful routes:

NEW
----
GET `partialInfo` : take a `nickname` as query and send back a partial user's information (nickname, eloScore, id). Throw a `NOT FOUND` response if no user by this nickname is found.

OLD
----
Please see swagger api for more infos.
GET `getAvatar/:id` : return streamable file of user's avatar identified by given id.
GET `getHistory/:id`: return JSON of game history

**Comment by Reaster0** [comment]
maybe i should merge one day because there is a lot of things i've made without merging lmao

**Comment by Reaster0** [comment]
wait it's already merged and done soo check it out! :D

**Comment by Ala-Na** [comment]
Can't wait to see =) It's becoming real 💪

**Comment by Ala-Na** [comment]
Just re-read subject and it say that status (online/offline/playing) should also be seen from user page. Right now, it's only displayed on chat (which was not mandatory).

**Comment by LesChats** [comment]
lucky for us is ez to do.... just need to decide on the way to display it.

**Comment by Reaster0** [comment]
> Just re-read subject and it say that status (online/offline/playing) should also be seen from user page. Right now, it's only displayed on chat (which was not mandatory).

i've putted the status in the friend list but i can put it too in the userpage no worries

**Comment by Reaster0** [comment]
done
